CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    seller_id INTEGER UNIQUE NOT NULL,
    is_verified_seller BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items (
    id SERIAL PRIMARY KEY,
    item_id INTEGER UNIQUE NOT NULL,
    seller_id INTEGER NOT NULL,
    name VARCHAR(500) NOT NULL,
    description TEXT NOT NULL,
    category INTEGER NOT NULL DEFAULT 0,
    images_qty INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_seller FOREIGN KEY (seller_id) REFERENCES users(seller_id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_items_seller_id ON items(seller_id);
CREATE INDEX IF NOT EXISTS idx_items_item_id ON items(item_id);
CREATE INDEX IF NOT EXISTS idx_users_seller_id ON users(seller_id);
